// Generated by CoffeeScript 1.6.3
module.exports = function(id, hostname, port) {
  /* browser-side*/

  var Promise, THREE, aspect, camera, canvas, client, container, dom, far, fov, height, near, radianRatio, radius, renderer, scene, toLatitude, toLongitude, transform, width, xhr;
  dom = require('dom');
  THREE = require('three');
  require('three-postprocessing');
  xhr = require('xhr');
  Promise = require('promise');
  client = require('vertex-client');
  container = dom('body').append('<div></div>').css({
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: '0px',
    left: '0px'
  });
  width = 800;
  height = 600;
  fov = 60;
  aspect = width / height;
  near = 0.1;
  far = 2000;
  renderer = new THREE.WebGLRenderer({
    antialias: false,
    alpha: false
  });
  camera = new THREE.PerspectiveCamera(fov, aspect, near, far);
  scene = new THREE.Scene;
  scene.fog = new THREE.FogExp2(0x251d15, 0.0018);
  scene.add(camera);
  camera.position.z = 750;
  renderer.setSize(width, height);
  renderer.setClearColor(0x050505, 1);
  canvas = renderer.domElement;
  container.append(canvas);
  canvas.style.width = '100%';
  canvas.style.height = '100%';
  radianRatio = Math.PI / 180;
  radius = 300;
  toLongitude = new THREE.Matrix4;
  toLatitude = new THREE.Matrix4;
  transform = function(longitude, latitude) {
    var vector;
    vector = new THREE.Vector3(0.0, 0.0, radius);
    toLongitude.makeRotationY(longitude * radianRatio);
    toLatitude.makeRotationX(-latitude * radianRatio);
    vector.applyMatrix4(toLatitude);
    vector.applyMatrix4(toLongitude);
    return vector;
  };
  return Promise.all(['/earth', '/visitors'].map(function(path) {
    return new Promise(function(resolve, reject) {
      return xhr({
        method: 'GET',
        url: path + ("?id=" + id)
      }, function(_arg) {
        var response, status;
        status = _arg.status, response = _arg.response;
        if (status === 200) {
          return resolve(JSON.parse(response));
        }
        return reject(new Error("" + path + " error status", status));
      }, reject);
    });
  })).then(function(_arg) {
    var animate, city, composer, country, earth, geometry, landMasses, lastPass, ll, material, me, particles, polygon, region, renderModel, renderTarget, vertex, visitors, _i, _j, _k, _len, _len1, _len2, _ref;
    earth = _arg[0], visitors = _arg[1];
    landMasses = [];
    for (_i = 0, _len = earth.length; _i < _len; _i++) {
      polygon = earth[_i];
      material = new THREE.LineBasicMaterial({
        color: 0xffffff
      });
      geometry = new THREE.Geometry;
      for (_j = 0, _len1 = polygon.length; _j < _len1; _j++) {
        vertex = polygon[_j];
        geometry.vertices.push(transform(vertex[0], vertex[1]));
      }
      landMasses.push(polygon = new THREE.Line(geometry, material));
      scene.add(polygon);
    }
    material = new THREE.ParticleBasicMaterial({
      color: 0xffffff,
      size: 8,
      fog: false
    });
    geometry = new THREE.Geometry;
    particles = new THREE.ParticleSystem(geometry, material);
    scene.add(particles);
    for (_k = 0, _len2 = visitors.length; _k < _len2; _k++) {
      _ref = visitors[_k], country = _ref.country, region = _ref.region, city = _ref.city, ll = _ref.ll, me = _ref.me;
      if (me) {
        console.log(city, region, country, ll);
      }
      geometry.vertices.push(transform(ll[1], ll[0]));
    }
    animate = function() {
      var _l, _len3;
      try {
        requestAnimationFrame(animate);
      } catch (_error) {}
      if (canvas.width !== canvas.clientWidth || canvas.height !== canvas.clientHeight) {
        canvas.width = canvas.clientWidth;
        canvas.height = canvas.clientHeight;
        camera.aspect = canvas.width / canvas.height;
        camera.updateProjectionMatrix();
        renderer.setSize(canvas.width, canvas.height);
        composer.setSize(canvas.width, canvas.height);
      }
      renderer.initWebGLObjects(scene);
      renderer.autoClear = false;
      renderer.shadowMapEnabled = true;
      renderer.autoUpdateObjects = true;
      composer.render();
      for (_l = 0, _len3 = landMasses.length; _l < _len3; _l++) {
        polygon = landMasses[_l];
        polygon.rotation.x += 0.003;
        polygon.rotation.y += 0.03;
      }
      particles.rotation.x += 0.003;
      return particles.rotation.y += 0.03;
    };
    renderTarget = new THREE.WebGLRenderTarget(canvas.width, canvas.height, {
      minFilter: THREE.LinearFilter,
      magFilter: THREE.LinearFilter,
      format: THREE.RGBFormat,
      stencilBuffer: false
    });
    renderModel = new THREE.RenderPass(scene, camera);
    lastPass = new THREE.ShaderPass(THREE.CopyShader);
    composer = new THREE.EffectComposer(renderer, renderTarget);
    composer.addPass(renderModel);
    composer.addPass(lastPass);
    lastPass.renderToScreen = true;
    return animate();
  }, function(error) {
    return console.log(error);
  });
};
