// Generated by CoffeeScript 1.6.3
module.exports = function() {
  /* browser-side*/

  var Promise, visitors, xhr;
  xhr = require('xhr');
  Promise = require('promise');
  visitors = new Promise(function(resolve, reject) {
    return xhr({
      url: '/visitors'
    }, function(_arg) {
      var response, status;
      status = _arg.status, response = _arg.response;
      if (status === 200) {
        return resolve(JSON.parse(response));
      }
      return reject(new Error('could not get visitors list status:', status));
    }, reject);
  });
  return visitors.then(function(res) {
    return console.log({
      visitors: res
    });
  });
};
