// Generated by CoffeeScript 1.6.3
var db, name, uri, visitorSchema;

db = require('mongoose');

name = process.env.MONGODB_NAME || 'test';

uri = "mongodb://localhost/" + name;

db.connect(uri);

visitorSchema = db.Schema({
  timestamp: {
    type: Date,
    "default": function() {
      return Date.now();
    }
  },
  location: {
    range: {
      type: Array,
      "default": [0, 0]
    },
    country: {
      type: String,
      "default": ''
    },
    region: {
      type: String,
      "default": ''
    },
    city: {
      type: String,
      "default": ''
    },
    ll: {
      type: Array,
      "default": [0, 0]
    }
  }
});

module.exports = {
  Visitor: db.model('Visitor', visitorSchema)
};
