// Generated by CoffeeScript 1.6.3
var ShapeFile, earth, round, sf;

ShapeFile = require('node-shapelib-partial').ShapeFile;

round = function(value) {
  return Math.floor(value * 10) / 10;
};

earth = void 0;

sf = new ShapeFile;

sf.open('data/ne_50m_land', function(err, res) {
  return earth = res.shapes.map(function(shape) {
    return shape.vertices.map(function(vertex) {
      var lat, lon;
      lat = round(vertex[0]);
      lon = round(vertex[1]);
      return [lat, lon];
    });
  });
});

module.exports = function(app) {
  return app.get('/earth', function(req, res) {
    return res.send(earth);
  });
};
