// Generated by CoffeeScript 1.6.3
var define, hmmmmm;

define = require('ipso').define;

define({
  hmmmmm: function() {
    return {
      aaah: function() {
        return 'oooooh!';
      }
    };
  }
});

hmmmmm = require('hmmmmm');

console.log(hmmmmm.aaah());
