// Generated by CoffeeScript 1.6.3
var geoip, root;

geoip = require('geoip-lite');

require('vertex')({
  www: {
    allowRoot: true,
    root: root = function(opts, callback) {
      var ip, location;
      if (opts.path !== '/') {
        return callback(null, {
          statusCode: 404
        });
      }
      if (ip = opts.headers['x-real-ip']) {
        if (location = geoip.lookup(ip)) {
          console.log(location);
        }
      }
      return callback(null, {
        headers: {
          'Content-Type': 'text/html'
        },
        body: '<body style="background: #000000"></body>'
      });
    },
    listen: {
      port: process.env.WWW_PORT,
      hostname: 'localhost'
    }
  }
});

root.$www = {};
