// Generated by CoffeeScript 1.6.3
var geoip, root;

geoip = require('geoip-lite');

require('vertex')({
  www: {
    allowRoot: true,
    root: root = function(opts, callback) {
      console.log({
        IP: opts.headers['X-Real-IP']
      });
      return callback(null, {
        headers: {
          'Content-Type': 'text/html'
        },
        body: '<body style="background: #000000"></body>'
      });
    },
    listen: {
      port: process.env.WWW_PORT,
      hostname: 'localhost'
    }
  }
});

root.$www = {};
