// Generated by CoffeeScript 1.6.3
var root;

require('vertex')({
  www: {
    allowRoot: true,
    root: root = function(opts, callback) {
      return callback(null, {
        headers: {
          'Content-Type': 'text/html'
        },
        body: '<body style="background: #000000"></body>'
      });
    },
    listen: {
      port: 3000
    }
  }
});

root.$www = {};
