// Generated by CoffeeScript 1.6.3
var Visitor, geoip, randomIP;

Visitor = require('./database').Visitor;

geoip = require('geoip-lite');

randomIP = function() {
  var random;
  random = function() {
    return Math.floor(Math.random() * 254);
  };
  return "" + (random()) + "." + (random()) + "." + (random()) + "." + (random());
};

module.exports = function(app) {
  return app.get('/', function(req, res) {
    var ip;
    ip = req.headers['x-real-ip'];
    if (process.env.NODE_ENV !== 'production') {
      ip || (ip = randomIP());
    }
    return (new Visitor({
      location: geoip.lookup(ip)
    })).save(function() {
      return res.render('index');
    });
  });
};
