// Generated by CoffeeScript 1.6.3
var database, fs, geoip;

fs = require('fs');

geoip = require('geoip-lite');

database = require('./database');

module.exports = function(opts, callback) {
  var ip, location;
  if (opts.path !== '/') {
    return callback(null, {
      statusCode: 404
    });
  }
  if (ip = opts.headers['x-real-ip']) {
    if (location = geoip.lookup(ip)) {
      console.log({
        LOCATION: location
      });
    }
  }
  return callback(null, {
    headers: {
      'Content-Type': 'text/html'
    },
    body: "<body>\n    <script src=\"build\"></script>\n    <script src=\"client\"></script>\n</body>"
  });
};

module.exports.client = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/javascript'
    },
    body: "(\n" + (require('./client').toString()) + "\n).call(self);"
  });
};

module.exports.build = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/javascript'
    },
    body: fs.readFileSync(__dirname + '/../build/build.js').toString()
  });
};

module.exports.$www = {};

module.exports.build.$www = {
  cache: true
};

module.exports.client.$www = {
  cache: true
};
