// Generated by CoffeeScript 1.6.3
var ShapeFile, buildScript, database, earth, fs, geoip, round, sf;

fs = require('fs');

geoip = require('geoip-lite');

ShapeFile = require('node-shapelib-partial').ShapeFile;

database = require('./database');

module.exports = function(opts, callback) {
  var ip, randomIP, response, v;
  if (opts.path !== '/') {
    return callback(null, {
      statusCode: 404
    });
  }
  response = function() {
    return callback(null, {
      headers: {
        'Content-Type': 'text/html'
      },
      body: "<body>\n    <script src=\"build\"></script>\n    <script src=\"client\"></script>\n</body>"
    });
  };
  randomIP = function() {
    var random;
    random = function() {
      return Math.floor(Math.random() * 254);
    };
    return "" + (random()) + "." + (random()) + "." + (random()) + "." + (random());
  };
  ip = opts.headers['x-real-ip'];
  if (process.env.NODE_ENV !== 'production') {
    ip || (ip = randomIP());
  }
  if (ip) {
    v = new database.Visitor({
      location: geoip.lookup(ip)
    });
    return v.save(function() {
      return response();
    });
  } else {
    return response();
  }
};

module.exports.client = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/javascript'
    },
    body: "(\n" + (require('./client').toString()) + "\n).call(self);"
  });
};

buildScript = "" + (fs.readFileSync(__dirname + '/../build/build.js').toString()) + "\n\n//\n// something is chopping the last few chars off the build script delivery\n//\n";

module.exports.build = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/javascript'
    },
    body: buildScript
  });
};

module.exports.visitors = function(opts, callback) {
  return database.Visitor.find().exec(function(err, result) {
    return callback(null, result.map(function(v) {
      return {
        country: v.location.country,
        region: v.location.region,
        city: v.location.city,
        ll: v.location.ll
      };
    }));
  });
};

round = function(value) {
  return Math.floor(value * 10) / 10;
};

earth = void 0;

sf = new ShapeFile;

sf.open('data/ne_50m_land', function(err, res) {
  return earth = res.shapes.map(function(shape) {
    return shape.vertices.map(function(v) {
      return [round(v[0]), round(v[1])];
    });
  });
});

module.exports.earth = function(opts, callback) {
  return callback(null, earth);
};

module.exports.$www = {};

module.exports.visitors.$www = {};

module.exports.earth.$www = {};

module.exports.build.$www = {
  cache: true
};

module.exports.client.$www = {
  cache: true
};
