// Generated by CoffeeScript 1.6.3
var ShapeFile, buildScript, database, earth, fs, geoip, sf;

fs = require('fs');

geoip = require('geoip-lite');

ShapeFile = require('node-shapelib-partial').ShapeFile;

database = require('./database');

module.exports = function(opts, callback) {
  var ip, v;
  if (opts.path !== '/') {
    return callback(null, {
      statusCode: 404
    });
  }
  if (ip = opts.headers['x-real-ip']) {
    v = new database.Visitor({
      location: geoip.lookup(ip)
    });
    v.save(function() {});
  }
  return callback(null, {
    headers: {
      'Content-Type': 'text/html'
    },
    body: "<body>\n    <script src=\"build\"></script>\n    <script src=\"client\"></script>\n</body>"
  });
};

module.exports.client = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/javascript'
    },
    body: "(\n" + (require('./client').toString()) + "\n).call(self);"
  });
};

buildScript = "" + (fs.readFileSync(__dirname + '/../build/build.js').toString()) + "\n\n//\n// something is chopping the last few chars off the build script delivery\n//\n";

module.exports.build = function(opts, callback) {
  return callback(null, {
    headers: {
      'Content-Type': 'text/javascript'
    },
    body: buildScript
  });
};

module.exports.visitors = function(opts, callback) {
  return database.Visitor.find().exec(function(err, result) {
    return callback(null, result.map(function(v) {
      return {
        country: v.location.country,
        region: v.location.region,
        city: v.location.city,
        ll: v.location.ll
      };
    }));
  });
};

earth = void 0;

sf = new ShapeFile;

sf.open('data/ne_50m_land', function(err, shapes) {
  return earth = shapes.shapes.map(function(p) {
    return p.vertices.map(function(v) {
      return v.slice(0, 2);
    });
  });
});

module.exports.earth = function(opts, callback) {
  return callback(null, earth);
};

module.exports.$www = {};

module.exports.visitors.$www = {};

module.exports.earth.$www = {};

module.exports.build.$www = {
  cache: true
};

module.exports.client.$www = {
  cache: true
};
