// Generated by CoffeeScript 1.6.3
var Packager, normalize;

normalize = require('path').normalize;

Packager = require('cetera').Packager;

module.exports = function(app) {
  var packager;
  packager = new Packager;
  return packager.mount({
    app: app,
    name: 'client',
    src: normalize(__dirname + '/../lib/client'),
    scripts: ['main.js']
  });
};
