// Generated by CoffeeScript 1.6.3
var Packager, Visitor, app, express, geoip, normalize, packager;

normalize = require('path').normalize;

Packager = require('cetera').Packager;

Visitor = require('./database').Visitor;

express = require('express');

geoip = require('geoip-lite');

app = express();

app.set('view engine', 'jade');

app.use(express["static"](normalize(__dirname + '/../public')));

packager = new Packager;

packager.mount({
  app: app,
  name: 'client',
  src: normalize(__dirname + '/../lib/client'),
  scripts: ['main.js']
});

require('./earth')(app);

require('./visitors')(app);

app.get('/', function(req, res) {
  var ip, randomIP, v;
  randomIP = function() {
    var random;
    random = function() {
      return Math.floor(Math.random() * 254);
    };
    return "" + (random()) + "." + (random()) + "." + (random()) + "." + (random());
  };
  ip = req.headers['x-real-ip'];
  if (process.env.NODE_ENV !== 'production') {
    ip || (ip = randomIP());
  }
  v = new Visitor({
    location: geoip.lookup(ip)
  });
  return v.save(function() {
    return res.render('index');
  });
});

app.listen(process.env.WWW_PORT || 3000, 'localhost');
