// Generated by CoffeeScript 1.6.3
var app, express;

express = require('express');

app = express();

app.set('view engine', 'jade');

app.get('/', function(req, res) {
  return res.render('index');
});

app.listen(3000, 'localhost');
