// Generated by CoffeeScript 1.6.3
var Visitor;

Visitor = require('./database').Visitor;

module.exports = function(app) {
  return app.get('/visitors', function(req, res) {
    var id;
    id = req.session.visitor_id;
    return Visitor.find().exec(function(err, result) {
      if (err != null) {
        return res.send(500, err);
      }
      return res.send(result.map(function(v) {
        return {
          me: v._id.toString() === id,
          country: v.location.country,
          region: v.location.region,
          city: v.location.city,
          ll: v.location.ll
        };
      }));
    });
  });
};
